[package]
name = "rust-web-server"
version = "0.1.0"
authors = [ "Samuel Kyletoft <samuel@kyletoft.se>", "Eli Adelhut <hello@eli.nu>" ]
edition = "2021"

[dependencies]
rocket = { version = "0.5.0-rc.1", features = [ "json" ] }
serde = "1.0.136"
